%% generate_bubbles.m
%% 論文 "Realistic Rendering of Ice and Crack Propagations" に基づく気泡生成スクリプト
%% 
%% 概要:
%% このスクリプトは、氷の内部にリアルな気泡分布を生成します。
%% 論文の手法に従い、2種類の正規分布を組み合わせて使用します:
%%   1. 中心部に高密度で集中した小さい気泡群
%%   2. 氷全体に低密度で散らばった気泡群
%%
%% 出力:
%% CSVファイル (x, y, z, radius の形式)
%%
%% 使用方法:
%% 1. このスクリプトをMATLABで実行
%% 2. 生成されたCSVファイルをC++プログラムで読み込む

clear; clc; close all;

%% ============================================
%% パラメータ設定
%% ============================================

% 氷の球体のパラメータ
ice_radius = 16.5;          % 氷の半径
ice_center = [0, 0, 0];     % 氷の中心（生成時は原点、後でC++側で移動）

% 分布1: 中心部に集中した高密度の小さい気泡群
num_bubbles_center = 250;   % 中心部の気泡数
pos_std_center = 3.5;       % 位置の標準偏差（小さいほど中心に集中）
radius_mean_center = 0.10;  % 気泡半径の平均（小さく）
radius_std_center = 0.03;   % 気泡半径の標準偏差

% 分布2: 全体に散らばった低密度の気泡群
num_bubbles_spread = 100;   % 散らばった気泡数
pos_std_spread = 8.0;       % 位置の標準偏差（大きいほど広く分布）
radius_mean_spread = 0.15;  % 気泡半径の平均
radius_std_spread = 0.05;   % 気泡半径の標準偏差

% 気泡半径の制限
min_radius = 0.03;          % 最小半径（小さく）
max_radius = 0.30;          % 最大半径（小さく）

% 出力ファイル名
output_filename = 'bubbles.csv';

%% ============================================
%% 気泡生成関数
%% ============================================

function bubbles = generate_bubble_distribution(num_bubbles, ice_radius, ice_center, ...
                                                 pos_std, radius_mean, radius_std, ...
                                                 min_radius, max_radius)
    % 正規分布で気泡の位置を生成（中心を原点として）
    positions = randn(num_bubbles, 3) * pos_std;
    
    % 正規分布で気泡の半径を生成
    radii = randn(num_bubbles, 1) * radius_std + radius_mean;
    
    % 半径の制限を適用
    radii = max(min(radii, max_radius), min_radius);
    
    % 有効な気泡のみを保持（氷の内部に完全に収まるもの）
    valid_bubbles = [];
    margin = 0.3;  % 表面からのマージン
    
    for i = 1:num_bubbles
        pos = positions(i, :);
        r = radii(i);
        
        % 気泡の中心から氷の中心までの距離
        dist_from_center = norm(pos - ice_center);
        
        % 気泡が完全に氷の内部に収まっているか確認
        if dist_from_center + r + margin < ice_radius
            valid_bubbles = [valid_bubbles; pos, r];
        end
    end
    
    bubbles = valid_bubbles;
end

%% ============================================
%% 気泡の生成
%% ============================================

fprintf('=== 気泡生成開始 ===\n');

% 分布1: 中心部に集中した気泡
fprintf('分布1（中心集中・小さい気泡）を生成中...\n');
bubbles_center = generate_bubble_distribution(num_bubbles_center, ice_radius, ice_center, ...
                                               pos_std_center, radius_mean_center, radius_std_center, ...
                                               min_radius, max_radius);
fprintf('  有効な気泡数: %d / %d\n', size(bubbles_center, 1), num_bubbles_center);

% 分布2: 全体に散らばった気泡
fprintf('分布2（全体分布）を生成中...\n');
bubbles_spread = generate_bubble_distribution(num_bubbles_spread, ice_radius, ice_center, ...
                                               pos_std_spread, radius_mean_spread, radius_std_spread, ...
                                               min_radius, max_radius);
fprintf('  有効な気泡数: %d / %d\n', size(bubbles_spread, 1), num_bubbles_spread);

% 気泡を結合
all_bubbles = [bubbles_center; bubbles_spread];
fprintf('合計気泡数: %d\n', size(all_bubbles, 1));

% 統計情報を表示
fprintf('\n=== 気泡半径の統計 ===\n');
fprintf('最小半径: %.4f\n', min(all_bubbles(:, 4)));
fprintf('最大半径: %.4f\n', max(all_bubbles(:, 4)));
fprintf('平均半径: %.4f\n', mean(all_bubbles(:, 4)));

%% ============================================
%% CSVファイルに出力
%% ============================================

fprintf('\nCSVファイルに出力中: %s\n', output_filename);

% ヘッダーコメントを含むファイルを作成
fid = fopen(output_filename, 'w');
fprintf(fid, '# Bubble data generated by generate_bubbles.m\n');
fprintf(fid, '# Format: x, y, z, radius\n');
fprintf(fid, '# Ice radius: %.2f\n', ice_radius);
fprintf(fid, '# Total bubbles: %d\n', size(all_bubbles, 1));
fclose(fid);

% データを追加
dlmwrite(output_filename, all_bubbles, '-append', 'precision', '%.6f');

fprintf('=== 気泡生成完了 ===\n');

%% ============================================
%% 可視化（オプション）
%% ============================================

figure('Name', '気泡分布の可視化');

% 3Dプロット
subplot(1, 2, 1);
hold on;

% 氷の球体（ワイヤーフレーム）
[X, Y, Z] = sphere(20);
X = X * ice_radius; Y = Y * ice_radius; Z = Z * ice_radius;
surf(X, Y, Z, 'FaceAlpha', 0.1, 'EdgeAlpha', 0.3, 'FaceColor', 'cyan');

% 気泡をプロット（サイズを大きめに表示して見やすく）
scatter3(all_bubbles(:,1), all_bubbles(:,2), all_bubbles(:,3), ...
         all_bubbles(:,4)*500, 'b', 'filled', 'MarkerFaceAlpha', 0.5);

xlabel('X'); ylabel('Y'); zlabel('Z');
title('気泡の3D分布');
axis equal;
grid on;
view(45, 30);

% 断面図（XY平面、Z=0付近）
subplot(1, 2, 2);
hold on;

% Z座標が±2以内の気泡のみをプロット
z_slice = abs(all_bubbles(:,3)) < 2;
slice_bubbles = all_bubbles(z_slice, :);

% 氷の輪郭
theta = linspace(0, 2*pi, 100);
plot(ice_radius * cos(theta), ice_radius * sin(theta), 'c-', 'LineWidth', 2);

% 気泡を円でプロット
for i = 1:size(slice_bubbles, 1)
    pos = slice_bubbles(i, 1:2);
    r = slice_bubbles(i, 4);
    circle_theta = linspace(0, 2*pi, 30);
    plot(pos(1) + r*cos(circle_theta), pos(2) + r*sin(circle_theta), 'b-', 'LineWidth', 0.5);
end

xlabel('X'); ylabel('Y');
title('気泡の断面図 (Z ≈ 0)');
axis equal;
grid on;

fprintf('\n可視化完了。ウィンドウを確認してください。\n');