%% generate_bubbles_mesh.m
%% 論文 "Realistic Rendering of Ice and Crack Propagations" に基づく気泡生成スクリプト
%% メッシュのバウンディングボックスに合わせて気泡を生成
%%
%% 使用方法:
%% 1. bbox_min, bbox_max を ice.obj のバウンディングボックスに設定
%% 2. このスクリプトをMATLABで実行
%% 3. 生成されたCSVファイルをC++プログラムで読み込む

clear; clc; close all;

%% ============================================
%% パラメータ設定
%% ============================================

% メッシュのバウンディングボックス（C++プログラムの出力を参照）
% スケーリング後の値を使用すること
% 例: ice.obj を scale=10 で読み込んだ場合のバウンディングボックス
bbox_min = [-15, -30, -15];  % 最小座標
bbox_max = [15, 0, 15];      % 最大座標

% バウンディングボックスの中心とサイズ
bbox_center = (bbox_min + bbox_max) / 2;
bbox_size = bbox_max - bbox_min;
min_dim = min(bbox_size);

% 表面からのマージン（気泡が表面に接しないように）
margin_ratio = 0.1;  % バウンディングボックスサイズの10%
margin = margin_ratio * min_dim;

% 分布1: 中心部に集中した高密度の気泡群
num_bubbles_center = 200;            % 中心部の気泡数
pos_std_center = min_dim * 0.15;     % 位置の標準偏差
radius_mean_center = min_dim * 0.015; % 気泡半径の平均
radius_std_center = min_dim * 0.005;  % 気泡半径の標準偏差

% 分布2: 全体に散らばった低密度の気泡群
num_bubbles_spread = 100;            % 散らばった気泡数
pos_std_spread = min_dim * 0.3;      % 位置の標準偏差
radius_mean_spread = min_dim * 0.02;  % 気泡半径の平均
radius_std_spread = min_dim * 0.008;  % 気泡半径の標準偏差

% 気泡半径の制限
min_radius = min_dim * 0.005;
max_radius = min_dim * 0.05;

% 出力ファイル名
output_filename = 'bubbles_mesh.csv';

%% ============================================
%% 気泡生成関数
%% ============================================

function bubbles = generate_bubble_distribution(num_bubbles, bbox_min, bbox_max, ...
                                                 bbox_center, pos_std, ...
                                                 radius_mean, radius_std, ...
                                                 min_radius, max_radius, margin)
    % 正規分布で気泡の位置を生成（中心を原点として）
    positions = randn(num_bubbles, 3) * pos_std;
    positions = positions + bbox_center;
    
    % 正規分布で気泡の半径を生成
    radii = randn(num_bubbles, 1) * radius_std + radius_mean;
    
    % 半径の制限を適用
    radii = max(min(radii, max_radius), min_radius);
    
    % 有効な気泡のみを保持
    valid_bubbles = [];
    
    for i = 1:num_bubbles
        pos = positions(i, :);
        r = radii(i);
        
        % バウンディングボックス内かチェック
        inside = true;
        for j = 1:3
            if pos(j) - r < bbox_min(j) + margin || pos(j) + r > bbox_max(j) - margin
                inside = false;
                break;
            end
        end
        
        if inside
            valid_bubbles = [valid_bubbles; pos, r];
        end
    end
    
    bubbles = valid_bubbles;
end

%% ============================================
%% 気泡の生成
%% ============================================

fprintf('=== 気泡生成開始 ===\n');
fprintf('バウンディングボックス:\n');
fprintf('  Min: [%.2f, %.2f, %.2f]\n', bbox_min(1), bbox_min(2), bbox_min(3));
fprintf('  Max: [%.2f, %.2f, %.2f]\n', bbox_max(1), bbox_max(2), bbox_max(3));
fprintf('  Center: [%.2f, %.2f, %.2f]\n', bbox_center(1), bbox_center(2), bbox_center(3));
fprintf('  Size: [%.2f, %.2f, %.2f]\n', bbox_size(1), bbox_size(2), bbox_size(3));

% 分布1: 中心部に集中した気泡
fprintf('\n分布1（中心集中）を生成中...\n');
bubbles_center = generate_bubble_distribution(num_bubbles_center, bbox_min, bbox_max, ...
                                               bbox_center, pos_std_center, ...
                                               radius_mean_center, radius_std_center, ...
                                               min_radius, max_radius, margin);
fprintf('  有効な気泡数: %d / %d\n', size(bubbles_center, 1), num_bubbles_center);

% 分布2: 全体に散らばった気泡
fprintf('分布2（全体分布）を生成中...\n');
bubbles_spread = generate_bubble_distribution(num_bubbles_spread, bbox_min, bbox_max, ...
                                               bbox_center, pos_std_spread, ...
                                               radius_mean_spread, radius_std_spread, ...
                                               min_radius, max_radius, margin);
fprintf('  有効な気泡数: %d / %d\n', size(bubbles_spread, 1), num_bubbles_spread);

% 気泡を結合
all_bubbles = [bubbles_center; bubbles_spread];
fprintf('\n合計気泡数: %d\n', size(all_bubbles, 1));

% 統計情報を表示
if ~isempty(all_bubbles)
    fprintf('\n=== 気泡半径の統計 ===\n');
    fprintf('最小半径: %.4f\n', min(all_bubbles(:, 4)));
    fprintf('最大半径: %.4f\n', max(all_bubbles(:, 4)));
    fprintf('平均半径: %.4f\n', mean(all_bubbles(:, 4)));
end

%% ============================================
%% CSVファイルに出力
%% ============================================

fprintf('\nCSVファイルに出力中: %s\n', output_filename);

% ヘッダーコメントを含むファイルを作成
fid = fopen(output_filename, 'w');
fprintf(fid, '# Bubble data generated by generate_bubbles_mesh.m\n');
fprintf(fid, '# Format: x, y, z, radius\n');
fprintf(fid, '# Bounding box min: [%.4f, %.4f, %.4f]\n', bbox_min(1), bbox_min(2), bbox_min(3));
fprintf(fid, '# Bounding box max: [%.4f, %.4f, %.4f]\n', bbox_max(1), bbox_max(2), bbox_max(3));
fprintf(fid, '# Total bubbles: %d\n', size(all_bubbles, 1));
fclose(fid);

% データを追加
if ~isempty(all_bubbles)
    dlmwrite(output_filename, all_bubbles, '-append', 'precision', '%.6f');
end

fprintf('=== 気泡生成完了 ===\n');

%% ============================================
%% 可視化
%% ============================================

if ~isempty(all_bubbles)
    figure('Name', '気泡分布の可視化');

    % 3Dプロット
    subplot(1, 2, 1);
    hold on;

    % バウンディングボックスの描画
    vertices = [
        bbox_min(1), bbox_min(2), bbox_min(3);
        bbox_max(1), bbox_min(2), bbox_min(3);
        bbox_max(1), bbox_max(2), bbox_min(3);
        bbox_min(1), bbox_max(2), bbox_min(3);
        bbox_min(1), bbox_min(2), bbox_max(3);
        bbox_max(1), bbox_min(2), bbox_max(3);
        bbox_max(1), bbox_max(2), bbox_max(3);
        bbox_min(1), bbox_max(2), bbox_max(3);
    ];
    edges = [1 2; 2 3; 3 4; 4 1; 5 6; 6 7; 7 8; 8 5; 1 5; 2 6; 3 7; 4 8];
    for i = 1:size(edges, 1)
        plot3([vertices(edges(i,1),1), vertices(edges(i,2),1)], ...
              [vertices(edges(i,1),2), vertices(edges(i,2),2)], ...
              [vertices(edges(i,1),3), vertices(edges(i,2),3)], 'c-', 'LineWidth', 1);
    end

    % 気泡をプロット
    scatter3(all_bubbles(:,1), all_bubbles(:,2), all_bubbles(:,3), ...
             all_bubbles(:,4)*200, 'b', 'filled', 'MarkerFaceAlpha', 0.5);

    xlabel('X'); ylabel('Y'); zlabel('Z');
    title('気泡の3D分布');
    axis equal;
    grid on;
    view(45, 30);

    % XZ平面の断面図（Y = center付近）
    subplot(1, 2, 2);
    hold on;

    % Y座標が中心付近の気泡のみをプロット
    y_center = bbox_center(2);
    y_tolerance = bbox_size(2) * 0.1;
    y_slice = abs(all_bubbles(:,2) - y_center) < y_tolerance;
    slice_bubbles = all_bubbles(y_slice, :);

    % バウンディングボックスの輪郭
    plot([bbox_min(1), bbox_max(1), bbox_max(1), bbox_min(1), bbox_min(1)], ...
         [bbox_min(3), bbox_min(3), bbox_max(3), bbox_max(3), bbox_min(3)], 'c-', 'LineWidth', 2);

    % 気泡を円でプロット
    for i = 1:size(slice_bubbles, 1)
        pos = [slice_bubbles(i, 1), slice_bubbles(i, 3)];
        r = slice_bubbles(i, 4);
        theta = linspace(0, 2*pi, 30);
        plot(pos(1) + r*cos(theta), pos(2) + r*sin(theta), 'b-', 'LineWidth', 0.5);
    end

    xlabel('X'); ylabel('Z');
    title(sprintf('気泡の断面図 (Y ≈ %.1f)', y_center));
    axis equal;
    grid on;

    fprintf('\n可視化完了。ウィンドウを確認してください。\n');
end
